# Generated by Django 5.2.6 on 2026-07-17 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint', models.CharField(max_length=500)),
                ('reply', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.register')),
            ],
            options={
                'db_table': 'complaint',
            },
        ),
    ]
