# Generated by Django 5.2.6 on 2026-07-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=45)),
                ('option1', models.CharField(max_length=45)),
                ('option2', models.CharField(max_length=45)),
                ('option3', models.CharField(max_length=45)),
                ('option4', models.CharField(max_length=45)),
                ('correct_answer', models.CharField(db_column='correct answer', max_length=45)),
            ],
            options={
                'db_table': 'quiz',
            },
        ),
    ]
