# Generated by Django 5.2.6 on 2026-07-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=100)),
                ('organization_id', models.IntegerField()),
                ('register_id', models.IntegerField()),
                ('sendertype', models.CharField(max_length=30)),
                ('rectype', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'chat',
            },
        ),
    ]
