# Generated by Django 5.2.6 on 2026-07-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('credential_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('breach_source', models.CharField(blank=True, max_length=100, null=True)),
                ('breach_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'credential',
            },
        ),
        migrations.CreateModel(
            name='EmailScan',
            fields=[
                ('scan_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_content', models.TextField()),
                ('risk', models.CharField(max_length=20)),
                ('report', models.TextField()),
                ('recommendation', models.TextField()),
                ('scanned_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'email_scan',
            },
        ),
    ]
