# Generated by Django 5.2.6 on 2026-07-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Securityrecommendation',
            fields=[
                ('security_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'securityrecommendation',
            },
        ),
    ]
